version: "3.7"

services:
  #service 1: definition of mysql database
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passdemo
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    restart: always

  #service 2: definition of your spring-boot app
  survey: #it is just a name, which will be used only in this file.
    image: survey               #name of the image after dockerfile executes
    container_name: survey-app  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8080:8080"                       #docker containter port with your os port
    restart: always

    depends_on: #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/survey?createDatabaseIfNotExist=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: passdemo